name: Update repository description

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Update repo description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X PATCH \
            /repos/${{ github.repository }} \
            -f description='My new repository description'
